- name: Create instances for ansible project
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-049de8215a1b7877b"
    Insta_type: "t3.micro"
    sg_id: "sg-0ac0a4d72dc0142f5"
    ami_id: "ami-0220d79f3f480ecf5"
    servers:
      - mysql
      - backend
      - frontend
  tasks:
    - name: install Python dependencies
      ansible.builtin.pip:
        name:
        - boto3
        - botocore
        executable: pip3.9
    
    - name: Onboard 3 ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        # key_name:
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "{{Insta_type}}"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
          Environment: Dev
      loop: "{{ servers }}"